Repository Shiranuit/TimeManager, pull requests merged in 2021-11, with the labels that each got.

#3 Add files via upload
  spec/Maquette.pdf
Labels: documentation

#5 Add support for teams
  backend/config.js
  backend/lib/api/controllers/AuthController.js
  backend/lib/api/controllers/TeamController.js
  backend/lib/api/controllers/index.js
  backend/lib/api/funnel.js
  backend/lib/backend/backend.js
  backend/lib/core/repository/index.js
  backend/lib/core/repository/teamRepository.js
  backend/lib/core/security/tokenRepository.js
  backend/lib/core/security/userRepository.js
  backend/lib/errors/errorCodes.js
  database/00-tables/00_backend.sql
  database/00-tables/01_users.sql
  database/00-tables/02_clocks.sql
  database/00-tables/03_workingtimes.sql
  database/00-tables/04_teams.sql
  database/01-functions/00-array_unique.sql
  database/01-functions/list_user_teams.sql
  docker-compose.yml
Labels: enhancement

#7 Enhance user security
  backend/config.js
  backend/lib/api/controllers/AuthController.js
  backend/lib/api/controllers/SecurityController.js
  backend/lib/api/funnel.js
  backend/lib/core/security/userRepository.js
Labels: enhancement

#9 Rate Limiter
  backend/config.js
  backend/lib/api/funnel.js
  backend/lib/api/rateLimiter.js
  backend/lib/core/network/entrypoint.js
  backend/lib/errors/errorCodes.js
Labels: enhancement

#8 Add unit tests
  .github/actions/unit-tests/action.yml
  .github/workflows/pull_request.workflow.yml
  .github/workflows/push_master.workflow.yml
  backend/.mocharc.json
  backend/lib/api/controllers/AuthController.js
  backend/lib/api/controllers/ClockController.js
  backend/lib/api/controllers/SecurityController.js
  backend/lib/api/funnel.js
  backend/lib/api/rateLimiter.js
  backend/lib/services/postgres/postgres.js
  backend/lib/utils/prom.js
  backend/package-lock.json
  backend/package.json
  backend/test/api/controllers/AuthController.test.js
  backend/test/api/controllers/ClockController.test.js
  backend/test/api/controllers/SecurityController.test.js
  backend/test/api/funnel.test.js
  backend/test/backend/events/backendEventEmitter.test.js
  backend/test/core/repository/clockRepository.test.js
  backend/test/core/repository/teamRepository.test.js
  backend/test/core/repository/workingTimeRepositoy.test.js
  backend/test/core/security/tokenRepository.test.js
  backend/test/core/security/userRepository.test.js
  backend/test/core/security/vault.test.js
  backend/test/mocks/backend.mock.js
  backend/test/mocks/rateLimiter.mock.js
  backend/test/mocks/router.mock.js
  backend/test/restore-sinon.js
  backend/test/services/postgres/postgres.test.js
Labels: WIP

#12 Add Swagger documentation
  backend/lib/api/DocApi/index.html
Labels: documentation

#14 Frontend rework
  backend/config.js
  backend/lib/api/controllers/SecurityController.js
  backend/lib/api/controllers/TeamController.js
  backend/lib/core/repository/teamRepository.js
  backend/lib/core/security/userRepository.js
  backend/lib/errors/errorCodes.js
  frontend/src/components/NavBar.vue
  frontend/src/components/TeamManager.vue
  frontend/src/components/TeamSettings.vue
  frontend/src/components/UserChart.vue
  frontend/src/components/UserManager.vue
  frontend/src/components/UserProfileMenu.vue
  frontend/src/components/UserSettings.vue
  frontend/src/components/WorkingTime.vue
  frontend/src/router/index.js
  frontend/src/views/Login.vue
  frontend/src/views/Settings.vue
  frontend/src/views/TeamManagement.vue
  frontend/src/views/UserManagement.vue
Labels: enhancement

#15 Add swagger doc in YAML extension
  backend/lib/api/DocApi/docapi.yaml
Labels: documentation

#16 Deploy the swagger documentation
  Swagger/docapi.yaml
  backend/lib/api/DocApi/index.html
  docker-compose.yml
Labels: documentation, enhancement

#17 Swagger doc generation
  Swagger/.gitignore
  Swagger/GenSwagger.js
  Swagger/config.js
  Swagger/docapi.json
  Swagger/docapi.yaml
  Swagger/package-lock.json
  Swagger/package.json
  Swagger/template.json
  backend/config.js
  backend/lib/api/controllers/AuthController.js
  backend/lib/api/controllers/ClockController.js
  backend/lib/api/controllers/SecurityController.js
  backend/lib/api/controllers/TeamController.js
  backend/lib/api/controllers/WorkingTimeController.js
  backend/lib/errors/errorCodes.js
  backend/test/api/controllers/AuthController.test.js
  backend/test/api/controllers/SecurityController.test.js
  docker-compose.yml
  frontend/src/views/Login.vue
Labels: documentation, enhancement
